### ISSUE TITLE
net-im/psimedia-9999 несобирается

### ISSUE THREAD

**Issue by alexws54tk** [psi-im/psimedia#2]
net-im/psimedia-9999 в процессе сборки цели «gstprovider/gstelements/static/lib/libgstelements_static.a» уходит в рекурсию, наткнувшись на отсутствие исходников следующих либ:
- dev-qt/qtcore
- dev-qt/qtgui
- dev-qt/qtwidgets

[build.log](https://gist.github.com/alexws54tk/f17459f3ec5e04a0bf54/raw/9eb727a8881b735fa00d20ee0f90343f3a5b6644/build.log)

**Comment by Ri0n** [comment]
fixed
